services:
  - type: static
    name: careerquest
    buildCommand: npm install && npm run build
    staticPublishPath: dist/public
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
